# Site settings
title: RunnerWoo's Blog
description: > # this means to ignore newlines until "baseurl:"
  HELLO WORLD!
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://runnerwoo.github.io" # the base hostname & protocol for your site
url: "http://runnerwoo.com"
timezone: Asia/Shanghai

# Social account
twitter_username:
github_username:  uwyc
sina_username: SimpleThx
sina_uid: '3796655394'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
sass:
    style: compressed

# Friend links
friends: [
  {
    title: "隔壁老王的小窝 - 一个程序员的小窝",
    href: "http://best8023.com/"
  },
  {
    title: "代码咖啡",
    href: "//blog.csdn.net/wj_november/"
  },
  {
    title: "inerdstack - 简书",
    href: "http://www.jianshu.com/users/9b87ba5fc959/"
  }
]
