# Site settings
title: RunnerWoo's Blog
description: > # this means to ignore newlines until "baseurl:"
  HELLO WORLD!
timezone: Asia/Shanghai

# social links
github_username:  uwyc
rss: rss
sina_username: ruwyc

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
exclude:
  - CNAME
  - README.md
  - changelog.md
  - files
  - others

# Friend links
friends:
  - title: "隔壁老王的小窝 - 一个程序员的小窝"
    href: "http://best8023.com/"
  - title: " 程序员技术栈"
    href: "http://dmkf.xyz/"
  - title: "菜鸟码农升职记"
    href: "//blog.csdn.net/wj_november/"
  - title: "inerdstack - 简书"
    href: "http://www.jianshu.com/users/9b87ba5fc959/"
